output_dir: issues
access_token: YOUR_ACCESS_TOKEN
projects:
  - https://github.com/nasa/cFE
  - https://github.com/nasa/osal
  - https://github.com/nasa/SC
  - https://github.com/nasa/CS
  - https://github.com/nasa/CF
  - https://github.com/nasa/PSP
  - https://github.com/nasa/elf2cfetbl
  - https://github.com/nasa/cFS
